stages:
    - install
    - build
    - deploy 

install:
    stage: install
    script:
        - C:\Users\Jordan\AppData\Roaming\npm\node_modules\yarn\bin\yarn install
        - echo "Build successful"

build:
     stage: build
     script:
        - C:\Users\Jordan\AppData\Roaming\npm\node_modules\yarn\bin\yarn build
        - echo "Build successful"

deploy:
      stage: deploy
      script:  
        - docker build . -t front-end-cinema-system
        - echo "Build successful"